updated comment api (#70)
* Add lastest Page

* Comments backend

* Update page.tsx

Fix these prettier errors
Error: 'headerText' is never reassigned. Use 'const' instead.  prefer-const
Error: Replace `·?·`${topic.toUpperCase()}·|·LATEST`` with `⏎····?·`${topic.toUpperCase()}·|·LATEST`⏎···`  prettier/prettier

* Update schema.ts

Fix the Prettier errors
./src/app/api/comments/schema.ts
4:2  Error: Insert `·`  prettier/prettier

* Update page.tsx

Fix this error:
./src/app/stories/latest/page.tsx
25:27  Error: Delete `·`  prettier/prettier
26:40  Error: Delete `·`  prettier/prettier

* Update index.tsx

Fix this error:
./src/components/Header/index.tsx
23:9  Warning: JSDoc comments must contain complete sentences with a capital letter.
y > window.scrollY : last saved Y > current scrollY means scrolling up window.scrollY > 800(height of imag): scrolling event only apply after 800(heigh of imag ) window.scrollY == 0 : if scroll Y = 0 means hit the top apply the scroll up.  isaacscript/complete-sentences-jsdoc
31:11  Warning: JSDoc comments must contain complete sentences with a trailing period.
Safari case if Y greather maxY( whole page ) set as scrolling down style  isaacscript/complete-sentences-jsdoc
39:11  Warning: JSDoc comments must contain complete sentences with a trailing period.
Safari case if Y is less than equal to 0 (top of page) set as scrolling up style else regular case scrolling down style  isaacscript/complete-sentences-jsdoc
88:3  Warning: JSDoc comments must contain complete sentences with a capital letter.
useEffect tell React that your component needs to do something after render.  isaacscript/complete-sentences-jsdoc

* Update page.tsx

* Update page.tsx

* Update route.ts

* Update route.ts

* update comments backend

* small fix

* updated comment backend

* update

* update comments backend

* update2

* update3

* update4

* update5

* update6

* small fix

* count total number of comments/replies

* count total number of comments/replies

* update comment backend

* refactor code for count api

---------

Co-authored-by: luomi16 <254287020@qq.com>
Co-authored-by: Mi Luo <74528702+luomi16@users.noreply.github.com>
Co-authored-by: Hillary <hillaryhwang123@gmail.com>